services:
  backend:
    image: test:latest
    container_name: test_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]