apiVersion: v1
kind: Service
metadata:
  name: bootcamp-backend-service
spec:
  selector:
    app: bootcamp-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP